/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonDialog: typeof import('./../src/components/common/common-dialog/src/common-dialog.vue')['default']
    ElBadge: (typeof import('element-plus/es'))['ElBadge']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip']
    ExceptionBase: typeof import('./../src/components/exception-base.vue')['default']
    HoverContainer: typeof import('./../src/components/hover-container.vue')['default']
    IconEpBell: (typeof import('~icons/ep/bell'))['default']
    IconEpChromeFilled: typeof import('~icons/ep/chrome-filled')['default']
    IconEpFullScreen: (typeof import('~icons/ep/full-screen'))['default']
    IconEpSearch: (typeof import('~icons/ep/search'))['default']
    IconLocalAvatar: typeof import('~icons/local/avatar')['default']
    IconLocalExpand: typeof import('~icons/local/expand')['default']
    IconLocalFold: typeof import('~icons/local/fold')['default']
    IconLocalNetworkError: typeof import('~icons/local/network-error')['default']
    IconLocalNoPermission: typeof import('~icons/local/no-permission')['default']
    IconLocalNotFound: typeof import('~icons/local/not-found')['default']
    IconLocalServiceError: typeof import('~icons/local/service-error')['default']
    NavMenu: typeof import('./../src/components/nav-menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svg-icon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
