<template>
  <el-menu default-active="2" class="el-menu-vertical-demo">
    <el-sub-menu
      v-for="menu in menus"
      :key="menu.id"
      :index="menu.id.toString()"
    >
      <template #title>
        <el-icon><location /></el-icon>
        <span>{{ menu.name }}</span>
      </template>
      <!-- 子菜单项 -->
      <el-menu-item
        v-for="child in menu.children"
        :key="child.id"
        :index="child.id.toString()"
      >
        {{ child.name }}
      </el-menu-item>
    </el-sub-menu>
  </el-menu>
</template>

<script setup>
const userStore = useUserStore();

const menus = computed(() => userStore.menus);

/*
已知menus数据结构如下，请将整其动态渲染出来
    
        {
            "id": 576274661328005,
            "moduleId": 287209077970501,
            "parentId": 0,
            "code": "ndgzgl",
            "name": "年度工作管理",
            "alias": null,
            "type": "目录",
            "status": "启用",
            "icon": "icon-sc-cwhjiandu",
            "routeName": "",
            "routePath": "",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": null,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 2,
            "description": null,
            "children": [
                {
                    "id": 595732856288261,
                    "moduleId": 282634553976389,
                    "parentId": 576274661328005,
                    "code": "ytzj3",
                    "name": "议题征集",
                    "alias": null,
                    "type": "公共业务模块",
                    "status": "启用",
                    "icon": "",
                    "routeName": "advice-collection-list",
                    "routePath": "",
                    "routeParams": "",
                    "routeTarget": 1,
                    "dataSourceId": 596127140488197,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 1,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                },
                {
                    "id": 572017301419023,
                    "moduleId": 287209077970501,
                    "parentId": 576274661328005,
                    "code": "ndjdgzjh",
                    "name": "年度工作计划",
                    "alias": null,
                    "type": "菜单",
                    "status": "启用",
                    "icon": "",
                    "routeName": "standing-committee-supervise-annual-plan",
                    "routePath": "/standing-committee-supervise/annual-plan",
                    "routeParams": null,
                    "routeTarget": 1,
                    "dataSourceId": null,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 3,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                }
            ],
            "statusValue": 1
        },
        {
            "id": 584160197612549,
            "moduleId": 287209077970501,
            "parentId": 0,
            "code": "jdqlcgl",
            "name": "监督全流程管理",
            "alias": null,
            "type": "目录",
            "status": "启用",
            "icon": "icon-operation-folder",
            "routeName": "",
            "routePath": "",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": null,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 3,
            "description": null,
            "children": [
                {
                    "id": 576306459702533,
                    "moduleId": 287209077970501,
                    "parentId": 584160197612549,
                    "code": "qlcjd",
                    "name": "监督管理",
                    "alias": null,
                    "type": "公共业务模块",
                    "status": "启用",
                    "icon": "",
                    "routeName": "standing-committee-supervise-supervise-type",
                    "routePath": "",
                    "routeParams": "",
                    "routeTarget": 1,
                    "dataSourceId": 572029885821957,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 1,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                },
                {
                    "id": 572116608799749,
                    "moduleId": 282634553976389,
                    "parentId": 584160197612549,
                    "code": "cwhjdyjzj",
                    "name": "意见征集",
                    "alias": null,
                    "type": "公共业务模块",
                    "status": "启用",
                    "icon": "",
                    "routeName": "advice-collection-list",
                    "routePath": null,
                    "routeParams": null,
                    "routeTarget": 1,
                    "dataSourceId": 572116186035205,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 2,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                },
                {
                    "id": 572431873888264,
                    "moduleId": 287209077970501,
                    "parentId": 584160197612549,
                    "code": "syyj",
                    "name": "审议意见",
                    "alias": null,
                    "type": "菜单",
                    "status": "启用",
                    "icon": "",
                    "routeName": "standing-committee-consider-opinion-list",
                    "routePath": "/standing-committee-supervise/consider-opinion-list",
                    "routeParams": "",
                    "routeTarget": 1,
                    "dataSourceId": null,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 3,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                }
            ],
            "statusValue": 1
        },
        {
            "id": 581992628384773,
            "moduleId": 287209077970501,
            "parentId": 0,
            "code": "zxjdgl",
            "name": "专项监督管理",
            "alias": null,
            "type": "公共业务模块",
            "status": "启用",
            "icon": "icon-lz-zhongdianduban",
            "routeName": "standing-committee-supervise-supervise-type",
            "routePath": "",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": 584400688874501,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 5,
            "description": null,
            "children": [],
            "statusValue": 1
        },
        {
            "id": 572431873888266,
            "moduleId": 572373488928709,
            "parentId": 0,
            "code": "rwzhgl",
            "name": "任务执行管理",
            "alias": null,
            "type": "目录",
            "status": "启用",
            "icon": "icon-lz-huodong",
            "routeName": "",
            "routePath": "",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": null,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 6,
            "description": null,
            "children": [
                {
                    "id": 595097667380229,
                    "moduleId": 572373488928709,
                    "parentId": 572431873888266,
                    "code": "rwcj",
                    "name": "任务拆解",
                    "alias": null,
                    "type": "菜单",
                    "status": "启用",
                    "icon": "",
                    "routeName": "supervise-task-list",
                    "routePath": "/task-execution-manage/supervise-task-list",
                    "routeParams": "",
                    "routeTarget": 1,
                    "dataSourceId": null,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 0,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                },
                {
                    "id": 572431873888265,
                    "moduleId": 572373488928709,
                    "parentId": 572431873888266,
                    "code": "sjzdrw",
                    "name": "市级重大任务",
                    "alias": null,
                    "type": "菜单",
                    "status": "启用",
                    "icon": "",
                    "routeName": "city-level-task-list",
                    "routePath": "/task-execution-manage/city-level-task-list",
                    "routeParams": "",
                    "routeTarget": 1,
                    "dataSourceId": null,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 1,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                },
                {
                    "id": 572431873888267,
                    "moduleId": 572373488928709,
                    "parentId": 572431873888266,
                    "code": "dtjcyyj",
                    "name": "动态监测与预警",
                    "alias": null,
                    "type": "菜单",
                    "status": "启用",
                    "icon": "",
                    "routeName": "task-early-warning-list",
                    "routePath": "/task-execution-manage/task-early-warning-list",
                    "routeParams": "",
                    "routeTarget": 1,
                    "dataSourceId": null,
                    "dataSourceDetailId": null,
                    "routeCache": false,
                    "sortIndex": 2,
                    "description": null,
                    "children": [],
                    "statusValue": 1
                }
            ],
            "statusValue": 1
        },
        {
            "id": 574553480410117,
            "moduleId": 287209077970501,
            "parentId": 0,
            "code": "jdrcfx",
            "name": "监督热词分析",
            "alias": null,
            "type": "菜单",
            "status": "启用",
            "icon": "icon-lz-zhongdianduban",
            "routeName": "supervision-hot",
            "routePath": "/unified-supervision/supervision-hot",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": null,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 7,
            "description": null,
            "children": [],
            "statusValue": 1
        },
        {
            "id": 572778005152773,
            "moduleId": 287209077970501,
            "parentId": 0,
            "code": "gzwx",
            "name": "跟踪问效",
            "alias": null,
            "type": "菜单",
            "status": "启用",
            "icon": "icon-sc-yijianzonghezj",
            "routeName": "four-lists",
            "routePath": "/unified-supervision/four-lists",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": null,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 8,
            "description": null,
            "children": [],
            "statusValue": 1
        },
        {
            "id": 573938485187589,
            "moduleId": 287209077970501,
            "parentId": 0,
            "code": "jdsjdag",
            "name": "监督数据档案馆",
            "alias": null,
            "type": "菜单",
            "status": "启用",
            "icon": "icon-lz-lvzhidangan2",
            "routeName": "supervision-archives",
            "routePath": "/unified-supervision/supervision-archives",
            "routeParams": "",
            "routeTarget": 1,
            "dataSourceId": null,
            "dataSourceDetailId": null,
            "routeCache": false,
            "sortIndex": 9,
            "description": null,
            "children": [],
            "statusValue": 1
        }
    ]
*/
</script>
